# Generated by Django 4.2.6 on 2023-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('type', models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Earned', 'Earned'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Bereavement', 'Bereavement'), ('Compassionate', 'Compassionate'), ('Study', 'Study'), ('Unpaid', 'Unpaid'), ('Special', 'Special')], max_length=20)),
                ('reason', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_leave_set', to='employee.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_leave_set', to='employee.employee')),
            ],
        ),
    ]
