# Generated by Django 4.2.6 on 2023-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_employee_set', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='static/expense/proof')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expense_claim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_claim_proof_set', to='reimbursement.expenseclaim')),
            ],
        ),
    ]
