# Generated by Django 4.2.6 on 2023-11-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_remove_expenseclaim_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseproof',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='expenseproof',
            name='expense_claim',
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='proofs',
            field=models.ManyToManyField(to='reimbursement.expenseproof'),
        ),
    ]
