# Generated by Django 4.2.6 on 2023-11-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_remove_expenseproof_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseproof',
            old_name='proof',
            new_name='file',
        ),
    ]
