# Generated by Django 4.2.6 on 2023-10-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
