# Generated by Django 4.2.6 on 2023-11-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
        ('employee', '0004_alter_employee_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='designation.designation'),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
