# Generated by Django 4.2.6 on 2023-11-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='designation_set', to='user.organization')),
            ],
        ),
    ]
