# Generated by Django 4.2.6 on 2023-11-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('department', '0002_alter_department_org'),
        ('designation', '0002_alter_designation_org'),
        ('employee', '0006_alter_employee_org'),
        ('user', '0002_user_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employer_user_set', to='organization.organization'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
