# Generated by Django 4.2.6 on 2023-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_overtime_set', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer_overtime_set', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='punched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='punched_by_employee_set', to='employee.employee'),
        ),
    ]
