# Generated by Django 4.2.6 on 2023-11-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punched_by',
        ),
    ]
