# Generated by Django 4.2.6 on 2023-11-02 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_org'),
        ('attendance', '0003_remove_attendance_punched_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='punch_in',
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.DateField(default=datetime.date(2023, 11, 2)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CheckInOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.employee')),
            ],
        ),
    ]
