# Generated by Django 4.2.6 on 2023-11-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_org'),
        ('attendance', '0004_remove_attendance_punch_in_attendance_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceRegister',
        ),
        migrations.RenameModel(
            old_name='CheckInOutLog',
            new_name='InOutLog',
        ),
    ]
