# Generated by Django 4.2.6 on 2023-11-02 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_inoutlog_in_out_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_in', models.IntegerField(default=0)),
                ('grace_out', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inoutlog',
            name='in_out_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inoutlog',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.shift'),
            preserve_default=False,
        ),
    ]
