# Generated by Django 4.2.6 on 2023-11-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_shift_alter_inoutlog_in_out_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.shift'),
        ),
        migrations.AlterField(
            model_name='inoutlog',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.shift'),
        ),
    ]
