# Generated by Django 4.2.6 on 2023-10-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_org'),
        ('employee', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_department_set', to='employee.employee')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_set', to='user.organization')),
            ],
        ),
    ]
