# Generated by Django 4.2.6 on 2023-11-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_set', to='organization.organization'),
        ),
    ]
